version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    command: npm run start:dev

  web:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    volumes:
      - ./application:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - api
    command: npm run dev
