services:
  api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: nest-api
    ports:
      - "8098:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run start:dev

  web-dev:
    build:
      context: ./application
      dockerfile: Dockerfile.dev
    container_name: next-app
    ports:
      - "8099:3000"
    volumes:
      - ./application:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8098
    command: npm run dev
